language: node_js
node_js:
  - "6.1"
  - "6.0"
services: 
  - mongodb
  - docker
before_script:
  - npm install -g gulp
  #login to docker
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script: npm test
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh && ./deploy.sh
  on:
    branch: master
