language: node_js
node_js:
  - "6.1"
  - "6.0"
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: script
  script: curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "staging"}' -X POST https://registry.hub.docker.com/u/kwalter26/scoreit-node/trigger/40d5e8eb-2ea9-4077-9fca-1cf0bdbfade6/
  on:
    branch: master
