language: node_js
node_js:
  - "6.1"
  - "6.0"
services: 
  - mongodb
  - docker
before_script:
  - npm install -g gulp
  #login to docker
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script: gulp
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
