language: node_js
node_js:
  - "6.1"
  - "6.0"
services: mongodb
before_script:
- sudo apt-get -qq update
- sudo apt-get install -y curl
- npm install -g gulp
script: gulp
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
